server:
  port: 8081
  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        default-zone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      server:
        git:
          default-label: api-gateway
          uri: https://github.com/AlejBravo/microservices.git
          search-paths: config-data
  application:
    name: config-microservice
